### ISSUE TITLE
Doesn't work with input[type=time]

### ISSUE THREAD

**Issue by theoreichel** [acpmasquerade/bootstrap3-timepicker2#2]
On Chrome/Linux the following message is raised when changing time using popup:

```
The specified value '2:45 PM' does not conform to the required format.  The format is 'HH:mm', 'HH:mm:ss' or 'HH:mm:ss.SSS' where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999.
```

Therefore time cannot be changed if the input type is _time_.

**Comment by acpmasquerade** [comment]
Although been much late to respond, but for good: 
The original project has been updated to include bootstrap 3 support so this repo is no longer maintained. Please try: https://github.com/jdewit/bootstrap-timepicker
