### ISSUE TITLE
Can't navigate through hours, minutes and meridian with left and right arrows

### ISSUE THREAD

**Issue by ivansammartino** [acpmasquerade/bootstrap3-timepicker2#4]
Hi, and thanks for this Bootstrap timepicker :-)
I noticed that in the original Bootstrap 2.x version (http://jdewit.github.io/bootstrap-timepicker/) I can navigate through hours, minutes and meridian with left and right arrows, while I can't do this in your version... Please, can you fix this if you have spare time?

Thanks

**Comment by acpmasquerade** [comment]
you mean to navigate from Hour to minute field using the right arrow ,etc ?

**Comment by ivanhalen** [comment]
I mean navigate from hour to minute to "AM/PM" in the same field with left and right arrows (please see attached gif)
![move](https://cloud.githubusercontent.com/assets/835377/9491846/8439c778-4bf2-11e5-8d3e-8771f531dc4f.gif)

**Comment by acpmasquerade** [comment]
Though very late to respond, but for good :) 
The original project has been updated to include bootstrap 3 support so this repo is no longer maintained. Please try: https://github.com/jdewit/bootstrap-timepicker
